### GET request to example server
POST http://localhost:8080/general_market/api/v1/products/create
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 description",
    "price": 100.00
}
> {%
 client.global.set("product_id", response.body.id);
 %}
###